### ISSUE TITLE
如何用plug 链接网站？

### ISSUE THREAD

**Issue by okeyzero** [xiaoyuanxun/Mora-20-mint-script#1]

**Comment by xiaoyuanxun** [comment]
用 ii 登陆网站，给plug身份的principal添加一下写作者身份就行

**Comment by okeyzero** [comment]
可以详细一点吗 这个步骤 我这里看到的是小狐狸 用ii 有点不太懂 对这个不熟悉

**Comment by xiaoyuanxun** [comment]
![截屏2023-12-11 下午6 16 15](https://github.com/xiaoyuanxun/Mora-20-mint-script/assets/53613219/5a8597e0-1428-4174-9fb9-19486209d9e5)

从这里进到 planet settings 里面，找到Planet writer然后add
